/**
 * Vendor the web fonts into public/fonts so the app makes no third-party
 * requests at runtime.
 *
 *   node scripts/fetch-fonts.mjs
 *
 * Why: loading fonts from fonts.gstatic.com sends every player's IP address to
 * a third party on page load. Self-hosting removes that transfer entirely,
 * which is the difference between needing a consent story and not.
 *
 * Licensing: IBM Plex Sans, IBM Plex Mono and Bebas Neue are all SIL Open Font
 * License 1.1, which permits redistribution as long as the license and
 * copyright notice travel with the files. This script downloads those too.
 */
import { mkdir, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const out = join(root, "public", "fonts");

// A modern UA is what makes the Google Fonts API hand back woff2 instead of ttf.
const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36";

const FAMILIES = [
  { query: "IBM+Plex+Sans:wght@400;600;700", slug: "plex-sans" },
  { query: "IBM+Plex+Mono:wght@500;700", slug: "plex-mono" },
  { query: "Bebas+Neue", slug: "bebas-neue" },
];

// The UI is Latin-only (usernames are [A-Za-z0-9 _-]), so shipping Cyrillic,
// Greek and Vietnamese would be dead weight.
const KEEP_SUBSETS = new Set(["latin", "latin-ext"]);

const LICENSES = [
  { url: "https://raw.githubusercontent.com/google/fonts/main/ofl/ibmplexsans/OFL.txt", to: "OFL-IBM-Plex.txt" },
  { url: "https://raw.githubusercontent.com/google/fonts/main/ofl/bebasneue/OFL.txt", to: "OFL-Bebas-Neue.txt" },
];

async function get(url, asBuffer = false) {
  const res = await fetch(url, { headers: { "User-Agent": UA } });
  if (!res.ok) throw new Error(`${res.status} ${url}`);
  return asBuffer ? Buffer.from(await res.arrayBuffer()) : res.text();
}

await mkdir(out, { recursive: true });

const blocks = [];
let files = 0;

for (const family of FAMILIES) {
  const css = await get(`https://fonts.googleapis.com/css2?family=${family.query}&display=swap`);
  // Each @font-face is preceded by a /* subset */ comment.
  const parts = css.split("/*").slice(1);
  for (const part of parts) {
    const subset = part.slice(0, part.indexOf("*/")).trim();
    if (!KEEP_SUBSETS.has(subset)) continue;
    const face = part.slice(part.indexOf("*/") + 2);
    const weight = /font-weight:\s*(\d+)/.exec(face)?.[1] ?? "400";
    const style = /font-style:\s*(\w+)/.exec(face)?.[1] ?? "normal";
    const src = /url\((https:[^)]+)\)/.exec(face)?.[1];
    const range = /unicode-range:\s*([^;]+);/.exec(face)?.[1]?.trim();
    const familyName = /font-family:\s*'([^']+)'/.exec(face)?.[1];
    if (!src || !familyName) continue;

    const name = `${family.slug}-${weight}-${subset}.woff2`;
    await writeFile(join(out, name), await get(src, true));
    files += 1;
    blocks.push(
      [
        "@font-face {",
        `  font-family: "${familyName}";`,
        `  font-style: ${style};`,
        `  font-weight: ${weight};`,
        "  font-display: swap;",
        `  src: url("/fonts/${name}") format("woff2");`,
        range ? `  unicode-range: ${range};` : null,
        "}",
      ]
        .filter(Boolean)
        .join("\n"),
    );
    console.log(`- ${name}`);
  }
}

for (const license of LICENSES) {
  await writeFile(join(out, license.to), await get(license.url));
  console.log(`- ${license.to}`);
}

const header = `/*
 * Generated by scripts/fetch-fonts.mjs. Do not hand-edit.
 *
 * Self-hosted so the app makes no third-party requests. IBM Plex Sans, IBM Plex
 * Mono and Bebas Neue are SIL Open Font License 1.1; the license texts sit
 * beside these files as OFL-IBM-Plex.txt and OFL-Bebas-Neue.txt.
 */
`;

await writeFile(join(out, "fonts.css"), `${header}\n${blocks.join("\n\n")}\n`);
console.log(`- fonts.css (${blocks.length} faces, ${files} files)`);
